const listings40mcgill = [
    // {
    //   "id": 4011,
    //   "unitId": 4011,
    //   "sqft": 606,
    //   "price": 0,
    //   "numOfBeds": 1,
    //   "numOfBaths": 1,
    //   "balcony": true,
    //   "tub": false,
    //   "pantry": false,
    //   "terrace": false,
    //   "officeDen": false,
    //   "walkInCloset": false,
    //   "builtIns": false,
    //   "juliet": false,
    //   "modelSuite": false,
    //   "isFeatured": false,
    //   "barrierFree": false,
    //   "image": "Unit_1A.png",
    //   "property": "40mcgill",
    //   "onHoldExpires": null,
    //   "status": "Vacant"
    // },
    // {
    //   "id": 4012,
    //   "unitId": 4012,
    //   "sqft": 575,
    //   "price": 0,
    //   "numOfBeds": 1,
    //   "numOfBaths": 1,
    //   "balcony": true,
    //   "tub": false,
    //   "pantry": false,
    //   "terrace": false,
    //   "officeDen": false,
    //   "walkInCloset": false,
    //   "builtIns": false,
    //   "juliet": false,
    //   "modelSuite": false,
    //   "isFeatured": false,
    //   "barrierFree": false,
    //   "image": "Unit_1B.png",
    //   "property": "40mcgill",
    //   "onHoldExpires": null,
    //   "status": "Vacant"
    // },
    // {
    //   "id": 4013,
    //   "unitId": 4013,
    //   "sqft": 1239,
    //   "price": 0,
    //   "numOfBeds": 2,
    //   "numOfBaths": 2,
    //   "balcony": false,
    //   "tub": false,
    //   "pantry": false,
    //   "terrace": true,
    //   "officeDen": false,
    //   "walkInCloset": false,
    //   "builtIns": false,
    //   "juliet": false,
    //   "modelSuite": false,
    //   "isFeatured": false,
    //   "barrierFree": false,
    //   "image": "Unit_1C.png",
    //   "property": "40mcgill",
    //   "onHoldExpires": null,
    //   "status": "Vacant"
    // },
    {
      "id": 4021,
      "unitId": 4021,
      "sqft": 1210,
      "price": 0,
      "numOfBeds": 2,
      "numOfBaths": 2,
      "balcony": false,
      "tub": false,
      "pantry": false,
      "terrace": true,
      "officeDen": false,
      "walkInCloset": false,
      "builtIns": false,
      "juliet": false,
      "modelSuite": false,
      "isFeatured": true,
      "barrierFree": false,
      "image": "Unit_2A.png",
      "property": "40mcgill",
      "onHoldExpires": null,
      "status": "Vacant"
    },
    {
      "id": 4022,
      "unitId": 4022,
      "sqft": 1096,
      "price": 0,
      "numOfBeds": 2,
      "numOfBaths": 2,
      "balcony": false,
      "tub": false,
      "pantry": false,
      "terrace": true,
      "officeDen": false,
      "walkInCloset": false,
      "builtIns": false,
      "juliet": false,
      "modelSuite": false,
      "isFeatured": true,
      "barrierFree": false,
      "image": "Unit_2B.png",
      "property": "40mcgill",
      "onHoldExpires": null,
      "status": "Vacant"
    },
    {
      "id": 4031,
      "unitId": 4031,
      "sqft": 1234,
      "price": 0,
      "numOfBeds": 2,
      "numOfBaths": 2,
      "balcony": false,
      "tub": false,
      "pantry": false,
      "terrace": true,
      "officeDen": false,
      "walkInCloset": false,
      "builtIns": false,
      "juliet": false,
      "modelSuite": false,
      "isFeatured": true,
      "barrierFree": false,
      "image": "Unit_3A.png",
      "property": "40mcgill",
      "onHoldExpires": null,
      "status": "Vacant"
    },
    {
      "id": 4032,
      "unitId": 4032,
      "sqft": 1121,
      "price": 0,
      "numOfBeds": 2,
      "numOfBaths": 2,
      "balcony": false,
      "tub": false,
      "pantry": false,
      "terrace": true,
      "officeDen": false,
      "walkInCloset": false,
      "builtIns": false,
      "juliet": false,
      "modelSuite": false,
      "isFeatured": true,
      "barrierFree": false,
      "image": "Unit_3B.png",
      "property": "40mcgill",
      "onHoldExpires": null,
      "status": "Vacant"
    }
  ];

  export default listings40mcgill;